# Generated by Django 2.2.7 on 2019-11-06 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='~ Enter max 20 characters.', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(help_text='~ Upload .csv or .txt file, see About page for more informations!', upload_to='tables_inputs')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('service', models.CharField(choices=[('TVA', 'TVA')], default='TVA', help_text='~ Select for which service you want to upload a file.', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
