# Generated by Django 2.2.7 on 2019-11-07 15:00

import Interface.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(help_text='~ Upload .csv or .txt file, see About page for more informations!', upload_to='tables_inputs', validators=[Interface.models.validate_file]),
        ),
    ]
