# Generated by Django 2.2.7 on 2019-11-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0002_auto_20191107_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(help_text='~ Enter max 25 characters.', max_length=25),
        ),
    ]
