# Generated by Django 2.2.7 on 2019-11-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0003_auto_20191107_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='output_file',
            field=models.FileField(default='default.csv', upload_to=''),
        ),
    ]
